### PR TITLE
Update how-can-i-enable-detailed-logging.md

### PR DESCRIPTION
**Pull request by matteobaccan**
Hi

I have fixed link to slf4j and log4j manual

ciao
matteo

### CODE REVIEW

**Comment by lucastetreault** [comment]
@matteobaccan, thanks for fixing the links. This page probably needs an overhaul with the move to log4j2 in 5.17.0.

**Review by jbonofre — CHANGES_REQUESTED** [review]
As ActiveMQ 5.17.x upgraded to log4j2, maybe worth to mention log4j2 documentation.

Thoughts ?

**Comment by matteobaccan** [comment]
Hi

why not link the two pieces of documentation, explain that before 5.17 is used log4j and from 5.17 is used log4j2?

ciao
matteo

**Comment by jbonofre** [comment]
@matteobaccan yes, it's what I mean actually.

**Comment by jbonofre** [comment]
I gonna merge manually in order to update link to log4j2.

**Pull request closed without merging**
