### PR TITLE
[#8222] Add support page back in and as a menu item to the nav

### PR DESCRIPTION
**Pull request by mattrpav**

### CODE REVIEW

**Comment by gemmellr** [comment]
It looks like @jbertram consolidated similar content from multiple separate places into a common 'Report Issues' page linked from the nav menu in https://github.com/apache/activemq-website/commit/f0187a0f2e53ba154e93a5109f74967425370a7b, while refreshing things and generalising some pages to cover all the components.

This change essentially adds back one of the old pages, meaning most of the information is duplicated again across the two pages, which are now both linked from the nav menu right next to each other. With some of this restoration then being stale again  with broken links / not generalised / etc, since its basically just the old content restored.

I'd suggest either referencing from one page to the other for specific bits and removing any actual full duplications, or else just consolidating them into one single page since they largely overlap. Probably the latter.

If https://activemq.apache.org/support is listed high on google then I'd probably use that link, or at least redirect it.
Actually, looking, it seems like https://activemq.apache.org/can-i-get-commercial-support and https://activemq.apache.org/how-can-i-get-help are well-placed links that could possibly also be redirected to one of these pages or whichever remains.  E.g you can do redirects like: https://github.com/apache/activemq-website/blame/main/src/_5x_releases/activemq-5016001-release.md#L6-L7

**Comment by mattrpav** [comment]
Yep, I am working on putting some pages back with redirects. Some of the docs out there indicate some settings that will have Google update the page index with the redirected page-- specifically for can-i-get-commerical-support and how-can-i-get-help, etc. Those can go straight to /support.

I plan to clean-up the de-dupe as well.

I think Reporting Issues and Getting Help/Getting Started are different things. I think it makes sense to break up the flow of the pages to align with how users come into the product and then report bugs/feature requests etc once its running.

I'm reviewing other other communities as a guide as well.

**Comment by gemmellr** [comment]
Ok glad you are still working on it. As a placeholder, I'd have probably copied the updated version of the content from the new 'issues' page to 'support' rather than restoring the stale old version now there again, given all its broken links to various other pages and talk of Java 1.5 and patches etc.

**Comment by jbertram** [comment]
I can see an argument both ways for breaking out "Support" into it's own page. Generally speaking you need to report an issue in order to get support. Perhaps the "Reporting Issues" page should just be renamed "Support" and then we can have redirects from all the old pages to that one.

In any event, we definitely should not duplicate content on multiple pages. I've worked many hours to remove as much of that as I can.

Also, we already have a handful of mod_rewrite rules in `.htaccess`. That's probably the best place to add redirects for the old support pages.

**Comment by mattrpav** [comment]
I'm good with .htaccess  picking up redirects for the broken links. The support link 404'n was brought to my attention by multiple folks and my priority was restoring it to something. 

I'll submit an updated PR on organizing the community content by EOW.

**Comment by jbertram** [comment]
I went ahead and committed some changes that should sort this out. See https://github.com/apache/activemq-website/commit/2ad529595789808c8095d9745c5c40ab21ec5a8f.

**Pull request merged**
