### PR TITLE
Updated ActiveMQ monitoring with New Relic APM

### PR DESCRIPTION
**Pull request by sjyothi54**
Hey ActiveMQ devs,
We have many users on our platform who are using ActiveMQ and would like to instrument it. We’d love to provide a smooth experience for ActiveMQ users who need to use monitoring solutions, such as New Relic. Please see our [documentation here](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/jmx-monitoring-activemq/).
Please consider adding a link for your direct users to provide an option for New Relic.  For your convenience, we have submitted this PR with our proposed content.
Please feel free to let us know if you have any questions or concerns.
Thank you for your consideration.

### CODE REVIEW

**Comment by lucastetreault** [comment]
Nice! I might suggest sorting the list of 3rd part tools alphabetically to remove any perceived preference. It still leaves New Relic at the end though :)

**Comment by jbonofre** [comment]
LGTM, I propose to merge, we can do another PR to sort the tools alphabetically.

@lucastetreault is it OK for you ?

**Comment by lucastetreault** [comment]
@jbonofre of course!

**Comment by jbonofre** [comment]
@lucastetreault great, thanks !

**Comment by sjyothi54** [comment]
@jbonofre @lucastetreault Thank you

**Pull request merged**
