### PR TITLE
[AMQ-8593] Document the new staticfailover discovery agent

### PR DESCRIPTION
**Pull request by lucastetreault**
Note: Do not merge until [this PR](https://github.com/apache/activemq/pull/835) has been merged and released in 5.17.2. May need to update the version mentioned if it is released with 5.18.0 instead.

### CODE REVIEW

**Review by jbonofre — APPROVED** [review]

**Comment by rmannibucau** [comment]
Hi, was it merged by error, seems staticfailover is NOT in 5.18.3 binaries

**Comment by mattrpav** [comment]
I'm going to rebase that PR and see about getting into an upcoming release. _Adding_ a new uri handler is non-breaking and we should be able to get that in without a problem.

**Comment by rmannibucau** [comment]
@mattrpav agree and I'd love to get the new config to simplify the uri but immediately fixing the doc would be good too (let me know if you need me to do the pr)

**Comment by jbonofre** [comment]
And not sure it's very convenient though :)

**Comment by mattrpav** [comment]
@rmannibucau if you have time to take over the PR, that'd be great [#835](https://github.com/apache/activemq/pull/835) I have it marked for v6.1.0 in JIRA.

The PR needs to be re-based and tests confirmed to use both the new and the old discovery uri.

**Pull request merged**
