### PR TITLE
Remove 5.15 from current releases

### PR DESCRIPTION
**Pull request by lucastetreault**
As per recent discussion here: https://github.com/apache/activemq/pull/767

Also fixes date format of the Artemis 2.19.1 release to fix the news feed.

### CODE REVIEW

**Review by jbonofre — APPROVED** [review]

**Comment by gemmellr** [comment]
It should also be removed from the dist repo.

**Comment by lucastetreault** [comment]
> It should also be removed from the dist repo.

The download points to: https://archive.apache.org/dist/activemq/5.15.15/apache-activemq-5.15.15-bin.zip. Is that the repo you're saying it needs to be removed from?

**Comment by gemmellr** [comment]
No. The comment was [not clearly] aimed to @jbonofre rather than yourself.

Your link is to the archive, which archives published releases and should retain it (we cant edit the archive either way, only Infra), and is what the website updates to point links to for 'non-current' previous releases. I am talking about the dist.a.o repo that the files are published to initially before announcement, which populates the CDN for downloads. It should only retain the 'current' releases.

**Comment by jbonofre** [comment]
@gemmellr good point. I will remove the artifacts from dist. I do it now. Thanks.

**Pull request merged**
