### PR TITLE
Update jQuery and refactor Artemis commit reports to use it

### PR DESCRIPTION
**Pull request by jbertram**

### CODE REVIEW

**Comment by jbertram** [comment]
FWIW, I tried updating the CMS API docs to use the new jQuery but the update broke those docs.

**Comment by tabish121** [comment]
> FWIW, I tried updating the CMS API docs to use the new jQuery but the update broke those docs.

What did you try exactly?  I was able to build the docs but that uses an older v3.4.1 jquery so still not ideal but there doesn't seem to be a way to completely remove it from doxygen output (at least that I've been able to find).

Another option is to remove the docs from the site given the client is not actually maintained any longer.

**Comment by jbertram** [comment]
@tabish121, I manually changed a couple of the HTML files to reference the new jQuery library and used `serve.sh` to look at the result. Here's what `index.html` for the 3.9 docs looked like before the update:
image
And here's what it looked like after the update:
image

**Comment by jbertram** [comment]
FWIW, I'm all for removing stuff that's no longer maintained.

**Comment by tabish121** [comment]
I regenerated the API docs and dropped in a replacement v3.6.1 jquery.js file and it mostly works with one odd bit of floating index tooling.
Screenshot from 2022-09-07 13-27-27

**Pull request merged**
