### PR TITLE
Update message-groups.md

### PR DESCRIPTION
**Pull request by jbarotin**
Add example that show how to enable messageGroupHashBucket and simpleMessageGroupMapFactory though XML config

### CODE REVIEW

**Comment by clebertsuconic** [comment]
Did you have any difficult on building the website. Can you also call ./build.sh ?


if you had difficult on installing jekyll let me know and I can do the compilation for you. but if you do it yourself, the process would be easier.

**Comment by jbarotin** [comment]
I haven't tried to build for a simple markdown modification. Is that important ?

**Comment by clebertsuconic** [comment]
@jbarotin the website output is based on ./content and it's only effective after you build it.. and merge it..

if you don't build it.. someone else will have to build it. which is fine (if you are not successful on installing Jekyll, just say so).. I'm just saying if you can build it yourself it's a lot easier.

I suggest you read the README on https://github.com/apache/activemq-website

**Comment by clebertsuconic** [comment]
@gtully / @tabish121 can you guys review the content updated here before we can merge it?

if the content is fine I will do the build.

**Comment by jbarotin** [comment]
It's ok, I can do it (yeah a new tool I didn't heard about). I think I'll have some more stuff to add to the documentation.

I'm currently using a lot ActiveMQ and I spend lot of time to understand how it works. I hope share my understanding though editing the documentation .

**Comment by clebertsuconic** [comment]
@jbarotin also check the rendering of your changes using ./serve.sh it's quite useful.

**Comment by jbarotin** [comment]
Here we go, I've only commit the generated file associated to message-group

**Comment by clebertsuconic** [comment]
cool.. I will merge it..

however I will use my git-fu powers to squash your commits into one before merging it.

**Comment by clebertsuconic** [comment]
@jbarotin thanks for the contrib... it's live now.

**Pull request closed without merging**
