### PR TITLE
Updating broken links in contributing.md file

### PR DESCRIPTION
**Pull request by chughpiyush**
- Main change is in  [src/contributing.md file](https://github.com/apache/activemq-website/pull/23/files#diff-2ae0475a795566a4e458257361101328)

- I commited changes to both `src` and `content` folders.
- Ran `./build.sh` in the end again to be sure of any other changes. 

- The reason of my commit is - 404 Not found on some of the pages:
https://activemq.apache.org/Developers/becoming-a-committer.md
https://activemq.apache.org/CommunityCommunity/Community/discussion-forums.md

- Broken links exist on this page - https://activemq.apache.org/contributing

- These redirect to a Not Found page:
image
image

### CODE REVIEW

**Comment by clebertsuconic** [comment]
I think you should squah both commits in 1

can you do that?

**Comment by clebertsuconic** [comment]
never mind.. I can do that with some git-fu before merging it.

**Comment by clebertsuconic** [comment]
I'm confused.. your commit run is before the actual changes.. I'm confused

**Comment by chughpiyush** [comment]
> I think you should squah both commits in 1
> 
> can you do that?

done

**Comment by chughpiyush** [comment]
> I'm confused.. your commit run is before the actual changes.. I'm confused

I changed - Now I did my changes first and then ran `./build.sh` then committed everything together.

**Comment by chughpiyush** [comment]
@clebertsuconic Just wanted to follow up, is there something pending from my side that is stopping review/merge of this pull request?

**Comment by clebertsuconic** [comment]
You're contributting code I think. I'm not a lawyer but usually when you send Pull Requests you're accepting License Terms of your contributions.

**Comment by clebertsuconic** [comment]
commit-report was generated by software.. what was wrong with the links? perhaps i should fix the generator instead?

**Comment by clebertsuconic** [comment]
I see that you wanted to update the title on the report. Is that what you wanted?

The report is generated by https://github.com/rh-messaging/jira-git-report

it's better to update the report, and re-generate it.. instead of manually changing it.

**Comment by chughpiyush** [comment]
@clebertsuconic No, I haven't done any `commit-report` changes. My changes are only in [contributing.md file](https://github.com/apache/activemq-website/pull/23/files#diff-2ae0475a795566a4e458257361101328). 

The reason of my commit is - `404 Not found` on some of the pages:
https://activemq.apache.org/Developers/becoming-a-committer.md
https://activemq.apache.org/CommunityCommunity/Community/discussion-forums.md

These redirect to a `Not Found` page:
image
image

The changes in the other 6 files were done by `generator` itself. I didn't change anything in `/content` folder. I can remove these 6 files from the commit if you say so.

**Comment by chughpiyush** [comment]
Hey @clebertsuconic
Does my reply help and can I do anything else to get this PR merged?

**Comment by chughpiyush** [comment]
I'll create another PR with minimal changes required.

**Pull request closed without merging**
